module.exports = {
  apps: [
    {
      name: "shop-backend",
      cwd: "/root/shop/shop/backend",
      script: "dist/index.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      max_memory_restart: "512M",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/root/shop/shop/logs/backend-error.log",
      out_file: "/root/shop/shop/logs/backend-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "shop-worker",
      cwd: "/root/shop/shop/backend",
      script: "dist/worker.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "512M",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/root/shop/shop/logs/worker-error.log",
      out_file: "/root/shop/shop/logs/worker-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "shop-frontend",
      cwd: "/root/shop/shop/frontend",
      script: "node_modules/.bin/next",
      args: "start -p 5000",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5000,
        BACKEND_URL: "http://localhost:4000",
      },
      max_memory_restart: "1G",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/root/shop/shop/logs/frontend-error.log",
      out_file: "/root/shop/shop/logs/frontend-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
