"use client";

import { useState, useEffect, useCallback, lazy, Suspense } from "react";
import { useRouter, useParams } from "next/navigation";
import { api } from "@/lib/api";
import {
  Upload,
  X,
  Save,
  ArrowLeft,
  Trash2,
  Plus,
  Zap,
  AlertTriangle,
  Check,
  Loader2,
  ClipboardPaste,
  Search,
  Globe,
} from "lucide-react";
import Link from "next/link";

const RichTextEditor = lazy(() => import("@/components/RichTextEditor"));

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Category {
  id: string;
  name: string;
  slug: string;
}

interface ProductImage {
  id: string;
  url: string;
  alt?: string;
  position: number;
}

interface ProductFormData {
  name: string;
  slug: string;
  description: string;
  price: string;
  comparePrice: string;
  sku: string;
  barcode: string;
  videoUrl: string;
  stock: string;
  lowStockAlert: string;
  trackInventory: boolean;
  allowBackorder: boolean;
  categoryId: string;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  featured: boolean;
  isNew: boolean;
  isBestseller: boolean;
  badgeText: string;
  tags: string;
  hasVariants: boolean;
  weight: string;
  metaTitle: string;
  metaDescription: string;
  flashSalePrice: string;
  flashSaleEndsAt: string;
}

interface SpecRow {
  id: string;
  key: string;
  value: string;
}

interface VariantRow {
  id: string;
  name: string;
  size: string;
  color: string;
  material: string;
  price: string;
  stock: string;
  sku: string;
  weight: string;
  height: string;
  dimensions: string;
  description: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const generateSlugFromName = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const emptyVariant = (): VariantRow => ({
  id: crypto.randomUUID(),
  name: "",
  size: "",
  color: "",
  material: "",
  price: "",
  stock: "",
  sku: "",
  weight: "",
  height: "",
  dimensions: "",
  description: "",
});

const resolveImageUrl = (url: string) =>
  url.startsWith("http")
    ? url
    : `${process.env.NEXT_PUBLIC_API_URL || ""}${url}`;

const inputClass =
  "w-full px-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-900/10 focus:border-gray-400 text-gray-900 placeholder:text-gray-400";
const labelClass = "block text-sm font-medium text-gray-500 mb-1";
const cardClass = "bg-white rounded-lg border border-gray-200 p-6";

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function EditProductPage() {
  const router = useRouter();
  const params = useParams();
  const productId = params.id as string;

  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [uploadingImages, setUploadingImages] = useState(false);
  const [categories, setCategories] = useState<Category[]>([]);
  const [images, setImages] = useState<ProductImage[]>([]);
  const [variants, setVariants] = useState<VariantRow[]>([]);
  const [specifications, setSpecifications] = useState<SpecRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const [formData, setFormData] = useState<ProductFormData>({
    name: "",
    slug: "",
    description: "",
    price: "",
    comparePrice: "",
    sku: "",
    barcode: "",
    videoUrl: "",
    stock: "0",
    lowStockAlert: "5",
    trackInventory: true,
    allowBackorder: false,
    categoryId: "",
    status: "DRAFT",
    featured: false,
    isNew: false,
    isBestseller: false,
    badgeText: "",
    tags: "",
    hasVariants: false,
    weight: "",
    metaTitle: "",
    metaDescription: "",
    flashSalePrice: "",
    flashSaleEndsAt: "",
  });

  const [flashSaleEnabled, setFlashSaleEnabled] = useState(false);

  // ---- helpers to update form -------------------------------------------------
  const setField = <K extends keyof ProductFormData>(key: K, value: ProductFormData[K]) =>
    setFormData((prev) => ({ ...prev, [key]: value }));

  // Track whether SKU was auto-generated (don't overwrite manual edits)
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(false);

  const handleCategoryChange = async (categoryId: string) => {
    setField("categoryId", categoryId as any);
    // Only auto-generate if SKU is empty or was previously auto-generated
    if (categoryId && (skuAutoGenerated || !formData.sku)) {
      try {
        const { sku } = await api.admin.getNextSku(categoryId);
        setFormData((prev) => ({ ...prev, sku }));
        setSkuAutoGenerated(true);
      } catch (err) {
        console.error("Failed to generate SKU:", err);
      }
    }
  };

  const handleSkuChange = (value: string) => {
    setSkuAutoGenerated(value === "");
    setField("sku", value as any);
  };

  // ---- data loading -----------------------------------------------------------
  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [productId]);

  const loadData = async () => {
    setLoading(true);
    setError(null);
    setNotFound(false);

    try {
      const [productData, categoriesData]: [any, any] = await Promise.all([
        api.admin.getProduct(productId),
        api.admin.getCategories(),
      ]);

      setCategories(
        Array.isArray(categoriesData) ? categoriesData : categoriesData.categories || [],
      );

      const p = productData;

      setFormData({
        name: p.name || "",
        slug: p.slug || "",
        description: p.description || "",
        price: p.price != null ? String(p.price) : "",
        comparePrice: p.comparePrice != null ? String(p.comparePrice) : "",
        sku: p.sku || "",
        barcode: p.barcode || "",
        videoUrl: p.videoUrl || "",
        stock: String(p.stock ?? 0),
        lowStockAlert: String(p.lowStockAlert ?? 5),
        trackInventory: p.trackInventory ?? true,
        allowBackorder: p.allowBackorder ?? false,
        categoryId: p.category?.id || p.categoryId || "",
        status: p.status || "DRAFT",
        featured: p.featured ?? false,
        isNew: p.isNew ?? false,
        isBestseller: p.isBestseller ?? false,
        badgeText: p.badgeText || "",
        tags: Array.isArray(p.tags) ? p.tags.join(", ") : p.tags || "",
        hasVariants: p.hasVariants ?? false,
        weight: p.weight != null ? String(p.weight) : "",
        metaTitle: p.metaTitle || "",
        metaDescription: p.metaDescription || "",
        flashSalePrice: p.flashSalePrice ? String(Number(p.flashSalePrice)) : "",
        flashSaleEndsAt: p.flashSaleEndsAt ? new Date(p.flashSaleEndsAt).toISOString().slice(0, 16) : "",
      });

      if (p.flashSalePrice || p.flashSaleEndsAt) {
        setFlashSaleEnabled(true);
      }

      setImages(
        (p.images || []).map((img: any) => ({
          id: img.id,
          url: img.url,
          alt: img.alt || "",
          position: img.position ?? 0,
        })),
      );

      setVariants(
        (p.variants || []).map((v: any) => ({
          id: v.id || crypto.randomUUID(),
          name: v.name || "",
          size: v.size || "",
          color: v.color || "",
          material: v.material || "",
          price: v.price != null ? String(v.price) : "",
          stock: v.stock != null ? String(v.stock) : "",
          sku: v.sku || "",
          weight: v.weight != null ? String(v.weight) : "",
          height: v.height || "",
          dimensions: v.dimensions || "",
          description: v.description || "",
        })),
      );

      setSpecifications(
        Array.isArray(p.specifications)
          ? p.specifications.map((s: any) => ({ id: crypto.randomUUID(), key: s.key || "", value: s.value || "" }))
          : [],
      );
    } catch (err: any) {
      console.error("Failed to load product:", err);
      if (err?.status === 404 || err?.response?.status === 404) {
        setNotFound(true);
      } else {
        setError("Failed to load product. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  };

  // ---- image upload (immediate) -----------------------------------------------
  const uploadFiles = useCallback(
    async (files: File[]) => {
      if (!files.length) return;
      setUploadingImages(true);
      setError(null);
      try {
        const result: any = await api.admin.uploadProductImages(productId, files);
        const uploaded: ProductImage[] = (result.images || result || []).map(
          (img: any, idx: number) => ({
            id: img.id,
            url: img.url,
            alt: img.alt || "",
            position: img.position ?? images.length + idx,
          }),
        );
        setImages((prev) => [...prev, ...uploaded]);
      } catch (err) {
        console.error("Image upload failed:", err);
        setError("Failed to upload image(s). Please try again.");
      } finally {
        setUploadingImages(false);
      }
    },
    [productId, images.length],
  );

  // Global paste handler
  useEffect(() => {
    const handlePaste = (e: ClipboardEvent) => {
      const items = e.clipboardData?.items;
      if (!items) return;
      const files = Array.from(items)
        .filter((item) => item.type.startsWith("image/"))
        .map((item) => item.getAsFile())
        .filter(Boolean) as File[];
      if (files.length > 0) {
        e.preventDefault();
        uploadFiles(files);
      }
    };
    document.addEventListener("paste", handlePaste);
    return () => document.removeEventListener("paste", handlePaste);
  }, [uploadFiles]);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;
    uploadFiles(Array.from(files));
    e.target.value = "";
  };

  const removeImage = async (image: ProductImage) => {
    try {
      await api.admin.deleteProductImage(productId, image.id);
      setImages((prev) => prev.filter((img) => img.id !== image.id));
    } catch (err) {
      console.error("Failed to delete image:", err);
      setError("Failed to remove image. Please try again.");
    }
  };

  // ---- slug -------------------------------------------------------------------
  const generateSlug = () => {
    setField("slug", generateSlugFromName(formData.name));
  };

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const name = e.target.value;
    setFormData((prev) => ({
      ...prev,
      name,
      slug: generateSlugFromName(name),
    }));
  };

  // ---- variants ---------------------------------------------------------------
  const addVariant = () => setVariants((prev) => [...prev, emptyVariant()]);

  const quickAddVariants = () => {
    const sizes = ["S", "M", "L", "XL"];
    const newVariants = sizes.map((size) => ({
      ...emptyVariant(),
      name: `${formData.name || "Product"} - ${size}`,
      size,
      price: formData.price,
    }));
    setVariants((prev) => [...prev, ...newVariants]);
  };

  const updateVariant = (id: string, field: keyof VariantRow, value: string) =>
    setVariants((prev) =>
      prev.map((v) => (v.id === id ? { ...v, [field]: value } : v)),
    );

  const removeVariant = (id: string) =>
    setVariants((prev) => prev.filter((v) => v.id !== id));

  const [expandedVariant, setExpandedVariant] = useState<string | null>(null);

  const toggleHasVariants = (checked: boolean) => {
    if (!checked && variants.length > 0) {
      if (!confirm("This will delete all variants. Continue?")) return;
      setVariants([]);
    }
    setField("hasVariants", checked);
  };

  const variantsTotalStock = variants.reduce(
    (sum, v) => sum + (parseInt(v.stock) || 0),
    0,
  );

  // ---- submit -----------------------------------------------------------------
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError(null);
    setSuccess(false);

    try {
      const parsedLowStock = parseInt(formData.lowStockAlert);
      const payload: Record<string, any> = {
        name: formData.name,
        slug: formData.slug || undefined,
        description: formData.description || undefined,
        price: parseFloat(formData.price),
        comparePrice: formData.comparePrice
          ? parseFloat(formData.comparePrice)
          : null,
        sku: formData.sku || undefined,
        barcode: formData.barcode || undefined,
        videoUrl: formData.videoUrl || undefined,
        stock: formData.hasVariants ? variantsTotalStock : parseInt(formData.stock),
        lowStockAlert: isNaN(parsedLowStock) ? 5 : parsedLowStock,
        trackInventory: formData.trackInventory,
        allowBackorder: formData.allowBackorder,
        categoryId: formData.categoryId || undefined,
        status: formData.status,
        featured: formData.featured,
        isNew: formData.isNew,
        isBestseller: formData.isBestseller,
        badgeText: formData.badgeText || undefined,
        tags: formData.tags
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean),
        hasVariants: formData.hasVariants,
        weight: formData.weight ? parseFloat(formData.weight) : null,
        specifications: specifications.filter((s) => s.key.trim() && s.value.trim()).map(({ key, value }) => ({ key: key.trim(), value: value.trim() })) || null,
        metaTitle: formData.metaTitle || undefined,
        metaDescription: formData.metaDescription || undefined,
      };

      // Only send flash sale fields when flash sale is enabled
      if (flashSaleEnabled) {
        payload.flashSalePrice = formData.flashSalePrice ? parseFloat(formData.flashSalePrice) : null;
        payload.flashSaleEndsAt = formData.flashSaleEndsAt ? new Date(formData.flashSaleEndsAt).toISOString() : null;
      } else {
        payload.flashSalePrice = null;
        payload.flashSaleEndsAt = null;
      }

      await api.admin.updateProduct(productId, payload);

      if (formData.hasVariants) {
        try {
          const variantPayload = variants.map((v) => ({
            id: v.id,
            name: v.name,
            size: v.size || undefined,
            color: v.color || undefined,
            material: v.material || undefined,
            price: v.price ? parseFloat(v.price) : null,
            stock: v.stock ? parseInt(v.stock) : 0,
            sku: v.sku || undefined,
            weight: v.weight ? parseFloat(v.weight) : null,
            height: v.height || undefined,
            dimensions: v.dimensions || undefined,
            description: v.description || undefined,
          }));
          await api.admin.updateProductVariants(productId, variantPayload);
        } catch (varErr: any) {
          console.error("Variant save failed:", varErr);
          setError(varErr?.message || "Product saved but variant update failed.");
          setSaving(false);
          return;
        }
      }

      setSuccess(true);
      setTimeout(() => router.push("/admin/products"), 1000);
    } catch (err: any) {
      console.error("Failed to save product:", err);
      setError(err?.message || "Failed to save product. Please check your input and try again.");
    } finally {
      setSaving(false);
    }
  };

  // ---- delete -----------------------------------------------------------------
  const handleDelete = async () => {
    if (
      !confirm(
        "Are you sure you want to delete this product? This action cannot be undone.",
      )
    )
      return;

    setDeleting(true);
    setError(null);
    try {
      await api.admin.deleteProduct(productId);
      router.push("/admin/products");
    } catch (err) {
      console.error("Failed to delete product:", err);
      setError("Failed to delete product. Please try again.");
      setDeleting(false);
    }
  };

  // ---- loading skeleton -------------------------------------------------------
  if (loading) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center gap-4 mb-8">
          <div className="w-10 h-10 bg-gray-200 rounded-lg animate-pulse" />
          <div>
            <div className="h-7 w-48 bg-gray-200 rounded animate-pulse mb-2" />
            <div className="h-4 w-32 bg-gray-100 rounded animate-pulse" />
          </div>
        </div>
        <div className="space-y-6">
          {[1, 2, 3, 4].map((n) => (
            <div key={n} className={cardClass}>
              <div className="h-5 w-40 bg-gray-200 rounded animate-pulse mb-4" />
              <div className="space-y-3">
                <div className="h-10 bg-gray-100 rounded animate-pulse" />
                <div className="h-10 bg-gray-100 rounded animate-pulse" />
                {n === 1 && (
                  <div className="h-32 bg-gray-100 rounded animate-pulse" />
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // ---- not found --------------------------------------------------------------
  if (notFound) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center gap-4 mb-8">
          <Link
            href="/admin/products"
            className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-2xl font-semibold text-gray-900">Product Not Found</h1>
        </div>
        <div className={cardClass}>
          <div className="text-center py-12">
            <AlertTriangle className="w-12 h-12 text-gray-300 mx-auto mb-4" />
            <p className="text-gray-500 mb-4">
              The product you&apos;re looking for doesn&apos;t exist or has been removed.
            </p>
            <Link
              href="/admin/products"
              className="inline-flex items-center gap-2 px-4 py-2.5 bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Products
            </Link>
          </div>
        </div>
      </div>
    );
  }

  // ---- SERP preview -----------------------------------------------------------
  const serpTitle = formData.metaTitle || formData.name || "Product Title";
  const serpDesc =
    formData.metaDescription ||
    formData.description?.replace(/<[^>]*>/g, "").slice(0, 160) ||
    "Product description will appear here...";
  const serpUrl = `yourstore.com/products/${formData.slug || "product-slug"}`;

  // ---- render -----------------------------------------------------------------
  return (
    <div className="max-w-4xl mx-auto pb-28">
      {/* Header */}
      <div className="flex items-center gap-4 mb-6">
        <Link
          href="/admin/products"
          className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <div>
          <h1 className="text-2xl font-semibold text-gray-900">Edit Product</h1>
          <p className="text-sm text-gray-500">{formData.name || "Untitled product"}</p>
        </div>
      </div>

      {/* Messages */}
      {error && (
        <div className="mb-6 p-4 border border-red-200 rounded-lg flex items-center gap-3 bg-white">
          <AlertTriangle className="w-5 h-5 text-red-500 flex-shrink-0" />
          <p className="text-red-700 text-sm">{error}</p>
        </div>
      )}
      {success && (
        <div className="mb-6 p-4 border border-emerald-200 rounded-lg flex items-center gap-3 bg-white">
          <Check className="w-5 h-5 text-emerald-600 flex-shrink-0" />
          <p className="text-emerald-700 text-sm">Product updated successfully! Redirecting…</p>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* ------------------------------------------------------------------ */}
        {/* 1. Basic Information                                                */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Basic Information</h2>
          <div className="grid gap-4">
            <div>
              <label className={labelClass}>Product Name *</label>
              <input
                type="text"
                className={inputClass}
                value={formData.name}
                onChange={handleNameChange}
                required
                placeholder="e.g., Premium Silicone Massager"
              />
            </div>

            <div>
              <label className={labelClass}>URL Slug</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  className={`${inputClass} font-mono text-sm`}
                  value={formData.slug}
                  onChange={(e) => setField("slug", e.target.value)}
                  placeholder="product-url-slug"
                />
                <button
                  type="button"
                  onClick={generateSlug}
                  className="px-4 py-2.5 text-sm text-gray-700 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors whitespace-nowrap"
                >
                  Generate
                </button>
              </div>
            </div>

            <div>
              <label className={labelClass}>Description</label>
              <Suspense
                fallback={
                  <div className="w-full min-h-[200px] border border-gray-200 rounded-lg animate-pulse bg-gray-50" />
                }
              >
                <RichTextEditor
                  value={formData.description}
                  onChange={(html: string) => setField("description", html)}
                  placeholder="Describe your product… Paste images with Ctrl+V"
                />
              </Suspense>
            </div>
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 2. Images                                                           */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Images</h2>
            <span className="flex items-center gap-1.5 text-xs text-gray-400">
              <ClipboardPaste className="w-3.5 h-3.5" />
              Ctrl+V to paste images
            </span>
          </div>

          {uploadingImages && (
            <div className="flex items-center gap-2 mb-3 text-sm text-gray-600">
              <Loader2 className="w-4 h-4 animate-spin" />
              Uploading…
            </div>
          )}

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {images.map((image, index) => {
              const imgSrc = resolveImageUrl(image.url);
              return (
                <div
                  key={image.id}
                  className="relative aspect-square bg-gray-100 rounded-lg overflow-hidden group"
                >
                  <img
                    src={imgSrc}
                    alt={image.alt || ""}
                    className="w-full h-full object-cover"
                    onError={(e) => {
                      const target = e.currentTarget;
                      if (!target.dataset.retried) {
                        target.dataset.retried = "1";
                        target.src = image.url;
                      }
                    }}
                  />
                  <button
                    type="button"
                    onClick={() => removeImage(image)}
                    className="absolute top-2 right-2 p-1.5 bg-gray-900/80 text-white rounded-full opacity-0 group-hover:opacity-100 hover:bg-gray-900 transition-all"
                  >
                    <X className="w-3.5 h-3.5" />
                  </button>
                  {index === 0 && (
                    <div className="absolute bottom-2 left-2 px-2 py-0.5 bg-gray-900/80 text-white text-xs rounded font-medium">
                      Main
                    </div>
                  )}
                </div>
              );
            })}

            <label
              className={`aspect-square border-2 border-dashed rounded-lg flex flex-col items-center justify-center cursor-pointer transition-all ${
                uploadingImages
                  ? "opacity-50 pointer-events-none border-gray-200"
                  : "border-gray-300 hover:border-gray-400 hover:bg-gray-50"
              }`}
            >
              <Upload className="w-8 h-8 text-gray-400 mb-2" />
              <span className="text-sm text-gray-500 text-center px-2">Add Image</span>
              <input
                type="file"
                accept="image/*"
                multiple
                className="hidden"
                onChange={handleImageUpload}
                disabled={uploadingImages}
              />
            </label>
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 3. Pricing & Inventory                                              */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Pricing & Inventory</h2>
          <div className="grid sm:grid-cols-2 gap-4">
            <div>
              <label className={labelClass}>Price (UGX) *</label>
              <input
                type="number"
                className={inputClass}
                value={formData.price}
                onChange={(e) => setField("price", e.target.value)}
                required
                min="0"
                step="0.01"
                placeholder="0.00"
              />
            </div>
            <div>
              <label className={labelClass}>Compare Price (Original)</label>
              <input
                type="number"
                className={inputClass}
                value={formData.comparePrice}
                onChange={(e) => setField("comparePrice", e.target.value)}
                min="0"
                step="0.01"
                placeholder="Original price (optional)"
              />
              <p className="text-xs text-gray-400 mt-1">
                Set higher than price to show discount
              </p>
            </div>
            <div>
              <label className={labelClass}>SKU</label>
              <input
                type="text"
                className={`${inputClass} font-mono`}
                value={formData.sku}
                onChange={(e) => handleSkuChange(e.target.value)}
                placeholder="Auto-generated from category"
              />
            </div>
            <div>
              <label className={labelClass}>Barcode</label>
              <input
                type="text"
                className={`${inputClass} font-mono`}
                value={formData.barcode}
                onChange={(e) => setField("barcode", e.target.value)}
                placeholder="e.g., 123456789012"
              />
            </div>

            {/* Weight */}
            <div>
              <label className={labelClass}>Weight (grams)</label>
              <input
                type="number"
                className={inputClass}
                value={formData.weight}
                onChange={(e) => setField("weight", e.target.value)}
                min="0"
                step="0.01"
                placeholder="e.g., 150"
              />
            </div>

            {/* Stock */}
            <div>
              <label className={labelClass}>Stock Quantity</label>
              {formData.hasVariants ? (
                <div className="px-4 py-2.5 border border-gray-200 rounded-lg bg-gray-50 text-gray-500 text-sm">
                  Managed by variants — Total: {variantsTotalStock}
                </div>
              ) : (
                <input
                  type="number"
                  className={inputClass}
                  value={formData.stock}
                  onChange={(e) => setField("stock", e.target.value)}
                  min="0"
                />
              )}
            </div>
            <div>
              <label className={labelClass}>Low Stock Alert</label>
              <input
                type="number"
                className={inputClass}
                value={formData.lowStockAlert}
                onChange={(e) => setField("lowStockAlert", e.target.value)}
                min="0"
                placeholder="5"
              />
            </div>

            {/* Toggles */}
            <div className="flex items-center gap-6 sm:col-span-2 pt-2">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.trackInventory}
                  onChange={(e) => setField("trackInventory", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">Track Inventory</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.allowBackorder}
                  onChange={(e) => setField("allowBackorder", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">Allow Backorder</span>
              </label>
            </div>
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 3b. Flash Sale                                                      */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">
              ⚡ Flash Sale
            </h2>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={flashSaleEnabled}
                onChange={(e) => {
                  const checked = e.target.checked;
                  setFlashSaleEnabled(checked);
                  if (!checked) {
                    setField("flashSalePrice", "");
                    setField("flashSaleEndsAt", "");
                  }
                }}
                className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
              />
              <span className="text-sm text-gray-700">Enable flash sale</span>
            </label>
          </div>

          {flashSaleEnabled ? (
            <div className="space-y-4">
              <p className="text-xs text-gray-400">
                Set a discounted price and end date. Product will appear in the Flash Sale section on the homepage.
              </p>
              <div className="grid sm:grid-cols-2 gap-4">
                <div>
                  <label className={labelClass}>Flash Sale Price (UGX) *</label>
                  <input
                    type="number"
                    className={inputClass}
                    value={formData.flashSalePrice}
                    onChange={(e) => setField("flashSalePrice", e.target.value)}
                    min="0"
                    step="0.01"
                    placeholder="0.00"
                  />
                  {formData.flashSalePrice &&
                    formData.price &&
                    parseFloat(formData.flashSalePrice) >= parseFloat(formData.price) && (
                      <p className="text-xs text-red-500 mt-1 flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" />
                        Flash sale price must be less than the regular price ({formData.price})
                      </p>
                    )}
                </div>
                <div>
                  <label className={labelClass}>Sale Ends At *</label>
                  <input
                    type="datetime-local"
                    className={inputClass}
                    value={formData.flashSaleEndsAt}
                    onChange={(e) => setField("flashSaleEndsAt", e.target.value)}
                  />
                </div>
              </div>
            </div>
          ) : (
            <p className="text-sm text-gray-400">
              Enable flash sale to set a limited-time discounted price.
            </p>
          )}
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 4. Variants                                                         */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Variants</h2>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={formData.hasVariants}
                onChange={(e) => toggleHasVariants(e.target.checked)}
                className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
              />
              <span className="text-sm text-gray-700">This product has variants</span>
            </label>
          </div>

          {formData.hasVariants && (
            <>
              {variants.length > 0 && (
                <div className="space-y-3 mb-4">
                  {variants.map((v) => (
                    <div key={v.id} className="border border-gray-200 rounded-lg">
                      {/* Main row */}
                      <div className="flex items-center gap-2 p-3">
                        <button
                          type="button"
                          onClick={() => setExpandedVariant(expandedVariant === v.id ? null : v.id)}
                          className="p-1 text-gray-400 hover:text-gray-700 transition-colors"
                          title="Toggle details"
                        >
                          <svg className={`w-4 h-4 transition-transform ${expandedVariant === v.id ? "rotate-90" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                        </button>
                        <input type="text" className="w-28 px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.size} onChange={(e) => updateVariant(v.id, "size", e.target.value)} placeholder="Size" />
                        <input type="text" className="w-20 px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.color} onChange={(e) => updateVariant(v.id, "color", e.target.value)} placeholder="Color" />
                        <input type="number" className="w-24 px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.price} onChange={(e) => updateVariant(v.id, "price", e.target.value)} placeholder="Price" min="0" step="0.01" />
                        <input type="number" className="w-16 px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.stock} onChange={(e) => updateVariant(v.id, "stock", e.target.value)} placeholder="Stock" min="0" />
                        <span className="text-xs text-gray-400 bg-gray-50 px-2 py-1.5 rounded truncate max-w-[120px]" title={v.name || "Auto-generated"}>
                          {v.name || "—"}
                        </span>
                        <div className="ml-auto">
                          <button type="button" onClick={() => removeVariant(v.id)} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded transition-colors">
                            <X className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                      {/* Expanded details */}
                      {expandedVariant === v.id && (
                        <div className="border-t border-gray-100 p-3 bg-gray-50/50 space-y-3">
                          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Material</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.material} onChange={(e) => updateVariant(v.id, "material", e.target.value)} placeholder="e.g., Gel" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Weight (g)</label>
                              <input type="number" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.weight} onChange={(e) => updateVariant(v.id, "weight", e.target.value)} placeholder="e.g., 50" min="0" step="0.01" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Height</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.height} onChange={(e) => updateVariant(v.id, "height", e.target.value)} placeholder="e.g., 15cm" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Dimensions</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.dimensions} onChange={(e) => updateVariant(v.id, "dimensions", e.target.value)} placeholder="e.g., 10x5x3cm" />
                            </div>
                          </div>
                          <div className="grid grid-cols-2 gap-3">
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">SKU</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm font-mono focus:outline-none focus:border-gray-400" value={v.sku} onChange={(e) => updateVariant(v.id, "sku", e.target.value)} placeholder="SKU" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Description</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm focus:outline-none focus:border-gray-400" value={v.description} onChange={(e) => updateVariant(v.id, "description", e.target.value)} placeholder="Variant-specific description" />
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}

              {variants.length === 0 && (
                <p className="text-sm text-gray-400 mb-4">
                  No variants yet. Add one manually or use quick-add.
                </p>
              )}

              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={addVariant}
                  className="flex items-center gap-1.5 px-3 py-2 text-sm border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-700 transition-colors"
                >
                  <Plus className="w-4 h-4" />
                  Add Variant
                </button>
                <button
                  type="button"
                  onClick={quickAddVariants}
                  className="flex items-center gap-1.5 px-3 py-2 text-sm border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-700 transition-colors"
                >
                  <Zap className="w-4 h-4" />
                  Quick Add (S/M/L/XL)
                </button>
              </div>
            </>
          )}
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 4b. Specifications                                                  */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Specifications</h2>
          </div>
          {specifications.length > 0 && (
            <div className="space-y-2 mb-4">
              {specifications.map((spec) => (
                <div key={spec.id} className="flex gap-2 items-center">
                  <input
                    type="text"
                    className={`${inputClass} flex-1`}
                    value={spec.key}
                    onChange={(e) =>
                      setSpecifications((prev) =>
                        prev.map((s) => (s.id === spec.id ? { ...s, key: e.target.value } : s)),
                      )
                    }
                    placeholder="e.g., Material"
                  />
                  <input
                    type="text"
                    className={`${inputClass} flex-1`}
                    value={spec.value}
                    onChange={(e) =>
                      setSpecifications((prev) =>
                        prev.map((s) => (s.id === spec.id ? { ...s, value: e.target.value } : s)),
                      )
                    }
                    placeholder="e.g., Gel"
                  />
                  <button
                    type="button"
                    onClick={() => setSpecifications((prev) => prev.filter((s) => s.id !== spec.id))}
                    className="p-1.5 text-gray-400 hover:text-gray-900 hover:bg-gray-100 rounded transition-colors"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          )}
          <button
            type="button"
            onClick={() =>
              setSpecifications((prev) => [...prev, { id: crypto.randomUUID(), key: "", value: "" }])
            }
            className="flex items-center gap-1.5 px-3 py-2 border border-gray-200 rounded-lg text-sm text-gray-700 hover:bg-gray-50 transition-colors"
          >
            <Plus className="w-4 h-4" />
            Add Specification
          </button>
          {specifications.length === 0 && (
            <p className="text-sm text-gray-400 mt-2">
              Add product specifications like material, dimensions, skin type, etc.
            </p>
          )}
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 5. Organization                                                     */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Organization</h2>
          <div className="grid sm:grid-cols-2 gap-4">
            <div>
              <label className={labelClass}>Category</label>
              <select
                className={`${inputClass} bg-white`}
                value={formData.categoryId}
                onChange={(e) => handleCategoryChange(e.target.value)}
              >
                <option value="">Select category</option>
                {categories.map((cat) => (
                  <option key={cat.id} value={cat.id}>
                    {cat.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className={labelClass}>Status</label>
              <select
                className={`${inputClass} bg-white`}
                value={formData.status}
                onChange={(e) =>
                  setField("status", e.target.value as ProductFormData["status"])
                }
              >
                <option value="DRAFT">Draft — Not visible to customers</option>
                <option value="ACTIVE">Active — Visible in store</option>
                <option value="ARCHIVED">Archived — Hidden from store</option>
              </select>
            </div>
            <div className="sm:col-span-2">
              <label className={labelClass}>Tags</label>
              <input
                type="text"
                className={inputClass}
                value={formData.tags}
                onChange={(e) => setField("tags", e.target.value)}
                placeholder="vibrator, premium, bestseller"
              />
              <p className="text-xs text-gray-400 mt-1">Separate tags with commas</p>
            </div>

            {/* Flags */}
            <div className="sm:col-span-2 flex flex-wrap gap-x-6 gap-y-3 pt-2">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.featured}
                  onChange={(e) => setField("featured", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">Featured</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.isNew}
                  onChange={(e) => setField("isNew", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">New</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.isBestseller}
                  onChange={(e) => setField("isBestseller", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">Bestseller</span>
              </label>
            </div>

            <div>
              <label className={labelClass}>Badge Text</label>
              <input
                type="text"
                className={inputClass}
                value={formData.badgeText}
                onChange={(e) => setField("badgeText", e.target.value)}
                placeholder="e.g., Hot Deal"
              />
            </div>
            <div>
              <label className={labelClass}>Video URL</label>
              <input
                type="url"
                className={inputClass}
                value={formData.videoUrl}
                onChange={(e) => setField("videoUrl", e.target.value)}
                placeholder="https://youtube.com/watch?v=..."
              />
            </div>
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 6. SEO                                                              */}
        {/* ------------------------------------------------------------------ */}
        <div className={cardClass}>
          <h2 className="text-lg font-semibold text-gray-900 mb-4">SEO</h2>
          <div className="grid gap-4">
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className={labelClass}>Meta Title</label>
                <span
                  className={`text-xs ${
                    formData.metaTitle.length > 60 ? "text-red-500" : "text-gray-400"
                  }`}
                >
                  {formData.metaTitle.length}/60
                </span>
              </div>
              <input
                type="text"
                className={inputClass}
                value={formData.metaTitle}
                onChange={(e) => setField("metaTitle", e.target.value)}
                placeholder={formData.name || "Product title for search engines"}
              />
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className={labelClass}>Meta Description</label>
                <span
                  className={`text-xs ${
                    formData.metaDescription.length > 160 ? "text-red-500" : "text-gray-400"
                  }`}
                >
                  {formData.metaDescription.length}/160
                </span>
              </div>
              <textarea
                className={`${inputClass} resize-none`}
                rows={3}
                value={formData.metaDescription}
                onChange={(e) => setField("metaDescription", e.target.value)}
                placeholder="Brief description for search engine results"
              />
            </div>

            {/* SERP Preview */}
            <div className="mt-2 p-4 bg-gray-50 rounded-lg border border-gray-100">
              <p className="text-xs font-medium text-gray-500 mb-3 flex items-center gap-1.5">
                <Search className="w-3.5 h-3.5" />
                Search Engine Preview
              </p>
              <div className="space-y-1">
                <p className="text-blue-700 text-base font-medium leading-snug truncate">
                  {serpTitle}
                </p>
                <p className="text-green-700 text-xs flex items-center gap-1 truncate">
                  <Globe className="w-3 h-3 flex-shrink-0" />
                  {serpUrl}
                </p>
                <p className="text-gray-600 text-sm leading-relaxed line-clamp-2">
                  {serpDesc}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/* 7. Sticky Action Bar                                                */}
        {/* ------------------------------------------------------------------ */}
        <div className="fixed bottom-0 left-0 right-0 z-30">
          <div className="max-w-4xl mx-auto px-4 pb-4">
            <div className="flex items-center gap-3 bg-white p-4 rounded-lg border border-gray-200 shadow-lg">
              {/* Delete */}
              <button
                type="button"
                onClick={handleDelete}
                disabled={deleting}
                className="flex items-center gap-2 px-4 py-2.5 text-sm text-red-600 hover:bg-red-50 rounded-lg transition-colors disabled:opacity-50 mr-auto"
              >
                {deleting ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Trash2 className="w-4 h-4" />
                )}
                {deleting ? "Deleting…" : "Delete Product"}
              </button>

              {/* Cancel */}
              <Link
                href="/admin/products"
                className="px-4 py-2.5 text-sm text-gray-700 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
              >
                Cancel
              </Link>

              {/* Save */}
              <button
                type="submit"
                disabled={saving || uploadingImages}
                className="flex items-center gap-2 px-5 py-2.5 text-sm bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors disabled:opacity-50 font-medium"
              >
                {saving ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Saving…
                  </>
                ) : (
                  <>
                    <Save className="w-4 h-4" />
                    Save Changes
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  );
}
