"use client";

import { useState, useEffect, useCallback, useMemo, lazy, Suspense } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import {
  Upload,
  X,
  ArrowLeft,
  Star,
  AlertTriangle,
  Check,
  Loader2,
  Package,
  ClipboardPaste,
  Plus,
  Trash2,
  Zap,
  Search,
  Globe,
  Video,
} from "lucide-react";
import Link from "next/link";

const RichTextEditor = lazy(() => import("@/components/RichTextEditor"));

interface Category {
  id: string;
  name: string;
  slug: string;
}

interface ProductFormData {
  name: string;
  slug: string;
  description: string;
  price: string;
  comparePrice: string;
  sku: string;
  barcode: string;
  videoUrl: string;
  stock: string;
  lowStockAlert: string;
  trackInventory: boolean;
  allowBackorder: boolean;
  categoryId: string;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  featured: boolean;
  isNew: boolean;
  isBestseller: boolean;
  badgeText: string;
  tags: string;
  hasVariants: boolean;
  weight: string;
  metaTitle: string;
  metaDescription: string;
  flashSalePrice: string;
  flashSaleEndsAt: string;
}

interface SpecRow {
  id: string;
  key: string;
  value: string;
}

interface VariantRow {
  id: string;
  name: string;
  size: string;
  color: string;
  material: string;
  price: string;
  stock: string;
  sku: string;
  weight: string;
  height: string;
  dimensions: string;
  description: string;
}

const inputClass =
  "w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900/10 focus:border-gray-400 transition-colors";
const labelClass = "block text-sm text-gray-500 mb-1";

function generateId() {
  return Math.random().toString(36).slice(2, 10);
}

function buildVariantName(v: VariantRow): string {
  return [v.size, v.color, v.material].filter(Boolean).join(" / ");
}

export default function NewProductPage() {
  const router = useRouter();
  const [saving, setSaving] = useState(false);
  const [categories, setCategories] = useState<Category[]>([]);
  const [images, setImages] = useState<string[]>([]);
  const [imageFiles, setImageFiles] = useState<File[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [variants, setVariants] = useState<VariantRow[]>([]);
  const [specifications, setSpecifications] = useState<SpecRow[]>([]);
  const [priceTiers, setPriceTiers] = useState<Array<{ id: string; minQty: string; discount: string; label: string }>>([]);
  const [quickAddValue, setQuickAddValue] = useState("");
  const [quickAddField, setQuickAddField] = useState<"size" | "color" | "material">("size");

  const [formData, setFormData] = useState<ProductFormData>({
    name: "",
    slug: "",
    description: "",
    price: "",
    comparePrice: "",
    sku: "",
    barcode: "",
    videoUrl: "",
    stock: "0",
    lowStockAlert: "5",
    trackInventory: true,
    allowBackorder: false,
    categoryId: "",
    status: "DRAFT",
    featured: false,
    isNew: false,
    isBestseller: false,
    badgeText: "",
    tags: "",
    hasVariants: false,
    weight: "",
    metaTitle: "",
    metaDescription: "",
    flashSalePrice: "",
    flashSaleEndsAt: "",
  });

  const [flashSaleEnabled, setFlashSaleEnabled] = useState(false);

  const variantTotalStock = useMemo(
    () => variants.reduce((sum, v) => sum + (parseInt(v.stock) || 0), 0),
    [variants],
  );

  useEffect(() => {
    loadCategories();
  }, []);

  const addFiles = useCallback((files: File[]) => {
    const newUrls = files.map((f) => URL.createObjectURL(f));
    setImages((prev) => [...prev, ...newUrls]);
    setImageFiles((prev) => [...prev, ...files]);
  }, []);

  useEffect(() => {
    const handlePaste = (e: ClipboardEvent) => {
      const items = e.clipboardData?.items;
      if (!items) return;
      const pasted = Array.from(items)
        .filter((item) => item.type.startsWith("image/"))
        .map((item) => item.getAsFile())
        .filter(Boolean) as File[];
      if (pasted.length > 0) {
        e.preventDefault();
        addFiles(pasted);
      }
    };
    document.addEventListener("paste", handlePaste);
    return () => document.removeEventListener("paste", handlePaste);
  }, [addFiles]);

  const loadCategories = async () => {
    try {
      const data: any = await api.admin.getCategories();
      setCategories(Array.isArray(data) ? data : data.categories || []);
    } catch (err) {
      console.error("Failed to load categories:", err);
    }
  };

  // Track whether SKU was auto-generated (so we don't overwrite manual edits)
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(true);

  const handleCategoryChange = async (categoryId: string) => {
    updateField("categoryId", categoryId);
    if (categoryId && skuAutoGenerated) {
      try {
        const { sku } = await api.admin.getNextSku(categoryId);
        setFormData((prev) => ({ ...prev, sku }));
      } catch (err) {
        console.error("Failed to generate SKU:", err);
      }
    }
  };

  const handleSkuChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setSkuAutoGenerated(val === "");
    updateField("sku", val);
  };

  const generateSlug = (name: string) =>
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const name = e.target.value;
    setFormData((prev) => ({ ...prev, name, slug: generateSlug(name) }));
  };

  const updateField = (field: keyof ProductFormData, value: any) =>
    setFormData((prev) => ({ ...prev, [field]: value }));

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) addFiles(Array.from(e.target.files));
  };

  const removeImage = (index: number) => {
    setImages((prev) => prev.filter((_, i) => i !== index));
    setImageFiles((prev) => prev.filter((_, i) => i !== index));
  };

  // --- Variant helpers ---
  const emptyVariant = (): VariantRow => ({
    id: generateId(), name: "", size: "", color: "", material: "", price: "", stock: "0", sku: "",
    weight: "", height: "", dimensions: "", description: "",
  });

  const addVariant = () => setVariants((prev) => [...prev, emptyVariant()]);

  const updateVariant = (id: string, field: keyof VariantRow, value: string) =>
    setVariants((prev) =>
      prev.map((v) => {
        if (v.id !== id) return v;
        const updated = { ...v, [field]: value };
        if (field === "size" || field === "color" || field === "material") {
          updated.name = buildVariantName(updated);
        }
        return updated;
      }),
    );

  const removeVariant = (id: string) => setVariants((prev) => prev.filter((v) => v.id !== id));

  const [expandedVariant, setExpandedVariant] = useState<string | null>(null);

  const handleQuickAdd = () => {
    const values = quickAddValue
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (values.length === 0) return;
    const newRows: VariantRow[] = values.map((val) => {
      const row: VariantRow = emptyVariant();
      row[quickAddField] = val;
      row.name = buildVariantName(row);
      return row;
    });
    setVariants((prev) => [...prev, ...newRows]);
    setQuickAddValue("");
  };

  // --- Submit ---
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError(null);
    setSuccess(false);

    try {
      const parsedLowStock = parseInt(formData.lowStockAlert);
      const payload: Record<string, any> = {
        name: formData.name,
        slug: formData.slug || undefined,
        description: formData.description || undefined,
        price: parseFloat(formData.price),
        comparePrice: formData.comparePrice ? parseFloat(formData.comparePrice) : null,
        sku: formData.sku || undefined,
        barcode: formData.barcode || undefined,
        videoUrl: formData.videoUrl || undefined,
        stock: formData.hasVariants ? variantTotalStock : parseInt(formData.stock),
        lowStockAlert: isNaN(parsedLowStock) ? 5 : parsedLowStock,
        trackInventory: formData.trackInventory,
        allowBackorder: formData.allowBackorder,
        categoryId: formData.categoryId || undefined,
        status: formData.status,
        featured: formData.featured,
        isNew: formData.isNew,
        isBestseller: formData.isBestseller,
        badgeText: formData.badgeText || undefined,
        hasVariants: formData.hasVariants,
        weight: formData.weight ? parseFloat(formData.weight) : null,
        specifications: specifications.filter((s) => s.key.trim() && s.value.trim()).map(({ key, value }) => ({ key: key.trim(), value: value.trim() })) || null,
        metaTitle: formData.metaTitle || undefined,
        metaDescription: formData.metaDescription || undefined,
        tags: formData.tags
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean),
      };

      // Only send flash sale fields when flash sale is enabled
      if (flashSaleEnabled) {
        payload.flashSalePrice = formData.flashSalePrice ? parseFloat(formData.flashSalePrice) : null;
        payload.flashSaleEndsAt = formData.flashSaleEndsAt ? new Date(formData.flashSaleEndsAt).toISOString() : null;
      } else {
        payload.flashSalePrice = null;
        payload.flashSaleEndsAt = null;
      }

      const product = await api.admin.createProduct(payload);

      // Upload images (non-fatal: product already created)
      if (imageFiles.length > 0) {
        try {
          await api.admin.uploadProductImages(product.id, imageFiles);
        } catch (imgErr) {
          console.error("Image upload failed:", imgErr);
        }
      }

      // Save variants (non-fatal: product already created)
      if (formData.hasVariants && variants.length > 0) {
        try {
          await api.admin.updateProductVariants(
            product.id,
            variants.map((v) => ({
              name: v.name,
              sku: v.sku || undefined,
              price: v.price ? parseFloat(v.price) : null,
              stock: parseInt(v.stock) || 0,
              size: v.size || undefined,
              color: v.color || undefined,
              material: v.material || undefined,
              weight: v.weight ? parseFloat(v.weight) : null,
              height: v.height || undefined,
              dimensions: v.dimensions || undefined,
              description: v.description || undefined,
            })),
          );
        } catch (varErr) {
          console.error("Variant save failed:", varErr);
        }
      }

      // Save price tiers
      if (priceTiers.length > 0) {
        try {
          const tiersPayload = priceTiers
            .filter((t) => t.minQty && t.discount)
            .map((t) => ({
              minQty: parseInt(t.minQty),
              discount: parseFloat(t.discount),
              label: t.label || null,
            }));
          if (tiersPayload.length > 0) {
            await api.admin.savePriceTiers(product.id, tiersPayload);
          }
        } catch (tierErr) {
          console.error("Price tiers save failed:", tierErr);
        }
      }

      setSuccess(true);
      setTimeout(() => router.push("/admin/products"), 1000);
    } catch (err: any) {
      console.error("Failed to save product:", err);
      setError(err?.message || "Failed to create product. Please check your input and try again.");
    } finally {
      setSaving(false);
    }
  };

  const serpUrl = formData.slug
    ? `ugsex.com/product/${formData.slug}`
    : "ugsex.com/product/your-product-slug";

  return (
    <div className="max-w-4xl mx-auto pb-28">
      {/* Header */}
      <div className="flex items-center gap-4 mb-6">
        <Link
          href="/admin/products"
          className="p-2 text-gray-500 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <div>
          <h1 className="text-2xl font-semibold text-gray-900">Add New Product</h1>
          <p className="text-sm text-gray-500">Create a new product listing</p>
        </div>
      </div>

      {/* Alerts */}
      {error && (
        <div className="mb-6 p-4 border border-gray-200 rounded-lg flex items-center gap-3">
          <AlertTriangle className="w-5 h-5 text-gray-900 flex-shrink-0" />
          <p className="text-sm text-gray-900">{error}</p>
        </div>
      )}
      {success && (
        <div className="mb-6 p-4 border border-gray-200 rounded-lg flex items-center gap-3">
          <Check className="w-5 h-5 text-gray-900 flex-shrink-0" />
          <p className="text-sm text-gray-900">Product created successfully! Redirecting…</p>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* ── 1. Basic Information ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Basic Information</h2>
          <div className="grid gap-4">
            <div>
              <label className={labelClass}>Product Name *</label>
              <input
                type="text"
                className={inputClass}
                value={formData.name}
                onChange={handleNameChange}
                required
                placeholder="e.g., Premium Wireless Headphones"
              />
            </div>
            <div>
              <label className={labelClass}>URL Slug</label>
              <input
                type="text"
                className={`${inputClass} font-mono`}
                value={formData.slug}
                onChange={(e) => updateField("slug", e.target.value)}
                placeholder="product-url-slug"
              />
            </div>
            <div>
              <label className={labelClass}>Description</label>
              <Suspense
                fallback={
                  <div className="w-full min-h-[200px] border border-gray-200 rounded-lg animate-pulse bg-gray-50" />
                }
              >
                <RichTextEditor
                  value={formData.description}
                  onChange={(html: string) => updateField("description", html)}
                  placeholder="Describe your product… Paste images with Ctrl+V"
                />
              </Suspense>
            </div>
          </div>
        </section>

        {/* ── 2. Images ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-gray-900">Images</h2>
            <span className="flex items-center gap-1.5 text-xs text-gray-400">
              <ClipboardPaste className="w-3.5 h-3.5" />
              Ctrl+V to paste
            </span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {images.map((url, index) => (
              <div key={index} className="relative aspect-square bg-gray-50 rounded-lg overflow-hidden group border border-gray-200">
                <img src={url} alt="" className="w-full h-full object-cover" />
                <button
                  type="button"
                  onClick={() => removeImage(index)}
                  className="absolute top-2 right-2 p-1 bg-gray-900 text-white rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
                {index === 0 && (
                  <span className="absolute bottom-2 left-2 px-2 py-0.5 bg-gray-900 text-white text-xs rounded">
                    Main
                  </span>
                )}
              </div>
            ))}
            <label className="aspect-square border-2 border-dashed border-gray-200 rounded-lg flex flex-col items-center justify-center cursor-pointer hover:border-gray-400 transition-colors">
              <Upload className="w-6 h-6 text-gray-400 mb-1.5" />
              <span className="text-xs text-gray-500">Add Image</span>
              <input type="file" accept="image/*" multiple className="hidden" onChange={handleImageUpload} />
            </label>
          </div>
        </section>

        {/* ── 3. Pricing & Inventory ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Pricing & Inventory</h2>
          <div className="grid sm:grid-cols-2 gap-x-6 gap-y-4">
            {/* Left column */}
            <div className="space-y-4">
              <div>
                <label className={labelClass}>Price (UGX) *</label>
                <input
                  type="number"
                  className={inputClass}
                  value={formData.price}
                  onChange={(e) => updateField("price", e.target.value)}
                  required
                  min="0"
                  step="0.01"
                  placeholder="0.00"
                />
              </div>
              <div>
                <label className={labelClass}>Compare Price</label>
                <input
                  type="number"
                  className={inputClass}
                  value={formData.comparePrice}
                  onChange={(e) => updateField("comparePrice", e.target.value)}
                  min="0"
                  step="0.01"
                  placeholder="Original price (optional)"
                />
                <p className="text-xs text-gray-400 mt-1">Set higher than price to show discount</p>
              </div>
              <div>
                <label className={labelClass}>SKU</label>
                <input
                  type="text"
                  className={`${inputClass} font-mono`}
                  value={formData.sku}
                  onChange={handleSkuChange}
                  placeholder="Auto-generated from category"
                />
              </div>
              <div>
                <label className={labelClass}>Barcode</label>
                <input
                  type="text"
                  className={`${inputClass} font-mono`}
                  value={formData.barcode}
                  onChange={(e) => updateField("barcode", e.target.value)}
                  placeholder="e.g., 1234567890123"
                />
              </div>
              <div>
                <label className={labelClass}>Weight (grams)</label>
                <input
                  type="number"
                  className={inputClass}
                  value={formData.weight}
                  onChange={(e) => updateField("weight", e.target.value)}
                  min="0"
                  step="0.01"
                  placeholder="e.g., 150"
                />
              </div>
            </div>

            {/* Right column */}
            <div className="space-y-4">
              <div>
                <label className={labelClass}>Stock Quantity</label>
                {formData.hasVariants && variants.length > 0 ? (
                  <div className="px-3 py-2 border border-gray-200 rounded-lg bg-gray-50 text-sm text-gray-500">
                    Managed by variants · Total: {variantTotalStock}
                  </div>
                ) : (
                  <input
                    type="number"
                    className={inputClass}
                    value={formData.stock}
                    onChange={(e) => updateField("stock", e.target.value)}
                    min="0"
                  />
                )}
              </div>
              <div>
                <label className={labelClass}>Low Stock Alert</label>
                <input
                  type="number"
                  className={inputClass}
                  value={formData.lowStockAlert}
                  onChange={(e) => updateField("lowStockAlert", e.target.value)}
                  min="0"
                  placeholder="5"
                />
              </div>
              <label className="flex items-center gap-2.5 pt-1 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.trackInventory}
                  onChange={(e) => updateField("trackInventory", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">Track inventory</span>
              </label>
              <label className="flex items-center gap-2.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.allowBackorder}
                  onChange={(e) => updateField("allowBackorder", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">Allow backorder</span>
              </label>
            </div>
          </div>
        </section>

        {/* ── 3b. Flash Sale ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-gray-900">
              ⚡ Flash Sale
            </h2>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={flashSaleEnabled}
                onChange={(e) => {
                  const checked = e.target.checked;
                  setFlashSaleEnabled(checked);
                  if (!checked) {
                    updateField("flashSalePrice", "");
                    updateField("flashSaleEndsAt", "");
                  }
                }}
                className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
              />
              <span className="text-sm text-gray-700">Enable flash sale</span>
            </label>
          </div>

          {flashSaleEnabled ? (
            <div className="space-y-4">
              <p className="text-xs text-gray-400">
                Set a discounted price and end date. Product will appear in the Flash Sale section on the homepage.
              </p>
              <div className="grid sm:grid-cols-2 gap-4">
                <div>
                  <label className={labelClass}>Flash Sale Price (UGX) *</label>
                  <input
                    type="number"
                    className={inputClass}
                    value={formData.flashSalePrice}
                    onChange={(e) => updateField("flashSalePrice", e.target.value)}
                    min="0"
                    step="0.01"
                    placeholder="0.00"
                  />
                  {formData.flashSalePrice &&
                    formData.price &&
                    parseFloat(formData.flashSalePrice) >= parseFloat(formData.price) && (
                      <p className="text-xs text-red-500 mt-1 flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" />
                        Flash sale price must be less than the regular price ({formData.price})
                      </p>
                    )}
                </div>
                <div>
                  <label className={labelClass}>Sale Ends At *</label>
                  <input
                    type="datetime-local"
                    className={inputClass}
                    value={formData.flashSaleEndsAt}
                    onChange={(e) => updateField("flashSaleEndsAt", e.target.value)}
                  />
                </div>
              </div>
            </div>
          ) : (
            <p className="text-sm text-gray-400">
              Enable flash sale to set a limited-time discounted price.
            </p>
          )}
        </section>

        {/* ── 4. Variants ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-gray-900">Variants</h2>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={formData.hasVariants}
                onChange={(e) => updateField("hasVariants", e.target.checked)}
                className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
              />
              <span className="text-sm text-gray-700">This product has variants</span>
            </label>
          </div>

          {formData.hasVariants && (
            <div className="space-y-4">
              {/* Quick Add */}
              <div className="flex gap-2 items-end">
                <div className="flex-1">
                  <label className={labelClass}>
                    <Zap className="w-3.5 h-3.5 inline mr-1" />
                    Quick Add
                  </label>
                  <div className="flex gap-2">
                    <select
                      value={quickAddField}
                      onChange={(e) => setQuickAddField(e.target.value as any)}
                      className="px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none focus:ring-2 focus:ring-gray-900/10"
                    >
                      <option value="size">Sizes</option>
                      <option value="color">Colors</option>
                      <option value="material">Materials</option>
                    </select>
                    <input
                      type="text"
                      className={`${inputClass} flex-1`}
                      value={quickAddValue}
                      onChange={(e) => setQuickAddValue(e.target.value)}
                      placeholder="e.g., S, M, L, XL"
                      onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), handleQuickAdd())}
                    />
                  </div>
                </div>
                <button
                  type="button"
                  onClick={handleQuickAdd}
                  className="px-4 py-2 border border-gray-200 rounded-lg text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                >
                  Generate
                </button>
              </div>

              {/* Variant list */}
              {variants.length > 0 && (
                <div className="space-y-3">
                  {variants.map((v) => (
                    <div key={v.id} className="border border-gray-200 rounded-lg">
                      {/* Main row */}
                      <div className="flex items-center gap-2 p-3">
                        <button
                          type="button"
                          onClick={() => setExpandedVariant(expandedVariant === v.id ? null : v.id)}
                          className="p-1 text-gray-400 hover:text-gray-700 transition-colors"
                          title="Toggle details"
                        >
                          <svg className={`w-4 h-4 transition-transform ${expandedVariant === v.id ? "rotate-90" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                        </button>
                        <input type="text" className="w-28 px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.size} onChange={(e) => updateVariant(v.id, "size", e.target.value)} placeholder="Size" />
                        <input type="text" className="w-20 px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.color} onChange={(e) => updateVariant(v.id, "color", e.target.value)} placeholder="Color" />
                        <input type="number" className="w-24 px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.price} onChange={(e) => updateVariant(v.id, "price", e.target.value)} placeholder="Price" min="0" step="0.01" />
                        <input type="number" className="w-16 px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.stock} onChange={(e) => updateVariant(v.id, "stock", e.target.value)} placeholder="Stock" min="0" />
                        <span className="text-xs text-gray-400 bg-gray-50 px-2 py-1.5 rounded truncate max-w-[120px]" title={v.name || "Auto-generated"}>
                          {v.name || "—"}
                        </span>
                        <div className="ml-auto">
                          <button type="button" onClick={() => removeVariant(v.id)} className="p-1.5 text-gray-400 hover:text-gray-900 hover:bg-gray-100 rounded transition-colors">
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                      {/* Expanded details */}
                      {expandedVariant === v.id && (
                        <div className="border-t border-gray-100 p-3 bg-gray-50/50 space-y-3">
                          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Material</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.material} onChange={(e) => updateVariant(v.id, "material", e.target.value)} placeholder="e.g., Gel" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Weight (g)</label>
                              <input type="number" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.weight} onChange={(e) => updateVariant(v.id, "weight", e.target.value)} placeholder="e.g., 50" min="0" step="0.01" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Height</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.height} onChange={(e) => updateVariant(v.id, "height", e.target.value)} placeholder="e.g., 15cm" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Dimensions</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.dimensions} onChange={(e) => updateVariant(v.id, "dimensions", e.target.value)} placeholder="e.g., 10x5x3cm" />
                            </div>
                          </div>
                          <div className="grid grid-cols-2 gap-3">
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">SKU</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm font-mono" value={v.sku} onChange={(e) => updateVariant(v.id, "sku", e.target.value)} placeholder="SKU" />
                            </div>
                            <div>
                              <label className="block text-xs text-gray-500 mb-1">Description</label>
                              <input type="text" className="w-full px-2 py-1.5 border border-gray-200 rounded text-sm" value={v.description} onChange={(e) => updateVariant(v.id, "description", e.target.value)} placeholder="Variant-specific description" />
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}

              <button
                type="button"
                onClick={addVariant}
                className="flex items-center gap-1.5 px-3 py-2 border border-gray-200 rounded-lg text-sm text-gray-700 hover:bg-gray-50 transition-colors"
              >
                <Plus className="w-4 h-4" />
                Add Variant
              </button>
            </div>
          )}

          {!formData.hasVariants && (
            <p className="text-sm text-gray-400">
              Enable variants to sell different sizes, colors, or materials of this product.
            </p>
          )}
        </section>

        {/* ── 4b. Specifications ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-gray-900">Specifications</h2>
          </div>
          {specifications.length > 0 && (
            <div className="space-y-2 mb-4">
              {specifications.map((spec) => (
                <div key={spec.id} className="flex gap-2 items-center">
                  <input
                    type="text"
                    className={`${inputClass} flex-1`}
                    value={spec.key}
                    onChange={(e) =>
                      setSpecifications((prev) =>
                        prev.map((s) => (s.id === spec.id ? { ...s, key: e.target.value } : s)),
                      )
                    }
                    placeholder="e.g., Material"
                  />
                  <input
                    type="text"
                    className={`${inputClass} flex-1`}
                    value={spec.value}
                    onChange={(e) =>
                      setSpecifications((prev) =>
                        prev.map((s) => (s.id === spec.id ? { ...s, value: e.target.value } : s)),
                      )
                    }
                    placeholder="e.g., Gel"
                  />
                  <button
                    type="button"
                    onClick={() => setSpecifications((prev) => prev.filter((s) => s.id !== spec.id))}
                    className="p-1.5 text-gray-400 hover:text-gray-900 hover:bg-gray-100 rounded transition-colors"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          )}
          <button
            type="button"
            onClick={() =>
              setSpecifications((prev) => [...prev, { id: generateId(), key: "", value: "" }])
            }
            className="flex items-center gap-1.5 px-3 py-2 border border-gray-200 rounded-lg text-sm text-gray-700 hover:bg-gray-50 transition-colors"
          >
            <Plus className="w-4 h-4" />
            Add Specification
          </button>
          {specifications.length === 0 && (
            <p className="text-sm text-gray-400 mt-2">
              Add product specifications like material, dimensions, skin type, etc.
            </p>
          )}
        </section>

        {/* ── 4c. Bulk Pricing / Price Tiers ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-gray-900">Bulk Pricing / Price Tiers</h2>
            {priceTiers.length > 0 && (
              <button
                type="button"
                onClick={() => {
                  if (confirm("Delete all price tiers?")) setPriceTiers([]);
                }}
                className="text-xs text-red-500 hover:text-red-700 transition-colors"
              >
                Clear All
              </button>
            )}
          </div>
          {priceTiers.length > 0 && (
            <div className="mb-4">
              <div className="grid grid-cols-[1fr_1fr_2fr_auto] gap-2 mb-2 text-[11px] text-gray-400 uppercase tracking-wider font-medium px-1">
                <span>Min Quantity</span>
                <span>Discount %</span>
                <span>Label</span>
                <span />
              </div>
              <div className="space-y-2">
                {priceTiers.map((tier) => (
                  <div key={tier.id} className="grid grid-cols-[1fr_1fr_2fr_auto] gap-2 items-center">
                    <input
                      type="number"
                      className={inputClass}
                      value={tier.minQty}
                      onChange={(e) => setPriceTiers((prev) => prev.map((t) => t.id === tier.id ? { ...t, minQty: e.target.value } : t))}
                      placeholder="e.g., 3"
                      min="2"
                    />
                    <input
                      type="number"
                      className={inputClass}
                      value={tier.discount}
                      onChange={(e) => setPriceTiers((prev) => prev.map((t) => t.id === tier.id ? { ...t, discount: e.target.value } : t))}
                      placeholder="e.g., 10"
                      min="0.01"
                      max="100"
                      step="0.01"
                    />
                    <input
                      type="text"
                      className={inputClass}
                      value={tier.label}
                      onChange={(e) => setPriceTiers((prev) => prev.map((t) => t.id === tier.id ? { ...t, label: e.target.value } : t))}
                      placeholder="e.g., Buy 3+ save 10%"
                    />
                    <button
                      type="button"
                      onClick={() => setPriceTiers((prev) => prev.filter((t) => t.id !== tier.id))}
                      className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded transition-colors"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}
          <button
            type="button"
            onClick={() => setPriceTiers((prev) => [...prev, { id: generateId(), minQty: "", discount: "", label: "" }])}
            className="flex items-center gap-1.5 px-3 py-2 border border-gray-200 rounded-lg text-sm text-gray-700 hover:bg-gray-50 transition-colors"
          >
            <Plus className="w-4 h-4" />
            Add Tier
          </button>
          {priceTiers.length === 0 && (
            <p className="text-sm text-gray-400 mt-2">
              Add quantity-based discounts. For example, &ldquo;Buy 3+ get 10% off.&rdquo;
            </p>
          )}
        </section>

        {/* ── 5. Organization ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Organization</h2>
          <div className="grid sm:grid-cols-2 gap-4">
            <div>
              <label className={labelClass}>Category</label>
              <select
                className={`${inputClass} bg-white`}
                value={formData.categoryId}
                onChange={(e) => handleCategoryChange(e.target.value)}
              >
                <option value="">Select category</option>
                {categories.map((cat) => (
                  <option key={cat.id} value={cat.id}>
                    {cat.name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className={labelClass}>Status</label>
              <select
                className={`${inputClass} bg-white`}
                value={formData.status}
                onChange={(e) => updateField("status", e.target.value)}
              >
                <option value="DRAFT">Draft – Not visible</option>
                <option value="ACTIVE">Active – Visible in store</option>
                <option value="ARCHIVED">Archived – Hidden</option>
              </select>
            </div>
            <div className="sm:col-span-2">
              <label className={labelClass}>Tags</label>
              <input
                type="text"
                className={inputClass}
                value={formData.tags}
                onChange={(e) => updateField("tags", e.target.value)}
                placeholder="premium, bestseller, wireless"
              />
              <p className="text-xs text-gray-400 mt-1">Separate tags with commas</p>
            </div>
          </div>

          {/* Badges row */}
          <div className="mt-5 pt-5 border-t border-gray-100">
            <label className={labelClass}>Badges</label>
            <div className="flex flex-wrap items-center gap-5 mt-1">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.featured}
                  onChange={(e) => updateField("featured", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <Star className="w-3.5 h-3.5 text-gray-400" />
                <span className="text-sm text-gray-700">Featured</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.isNew}
                  onChange={(e) => updateField("isNew", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">New</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.isBestseller}
                  onChange={(e) => updateField("isBestseller", e.target.checked)}
                  className="w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                />
                <span className="text-sm text-gray-700">Bestseller</span>
              </label>
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-500">Custom:</span>
                <input
                  type="text"
                  className="px-2.5 py-1.5 border border-gray-200 rounded-lg text-sm w-36"
                  value={formData.badgeText}
                  onChange={(e) => updateField("badgeText", e.target.value)}
                  placeholder="e.g., Limited Edition"
                />
              </div>
            </div>
          </div>

          {/* Video URL */}
          <div className="mt-5 pt-5 border-t border-gray-100">
            <label className={labelClass}>
              <Video className="w-3.5 h-3.5 inline mr-1" />
              Product Video URL (YouTube or direct link)
            </label>
            <input
              type="url"
              className={inputClass}
              value={formData.videoUrl}
              onChange={(e) => updateField("videoUrl", e.target.value)}
              placeholder="https://youtube.com/watch?v=..."
            />
            {formData.videoUrl && (() => {
              const ytMatch = formData.videoUrl.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/);
              if (ytMatch) {
                return (
                  <div className="mt-3 rounded-lg overflow-hidden border border-gray-200">
                    <img
                      src={`https://img.youtube.com/vi/${ytMatch[1]}/hqdefault.jpg`}
                      alt="Video thumbnail"
                      className="w-full h-auto"
                    />
                    <div className="px-3 py-2 bg-gray-50 text-xs text-gray-500 flex items-center gap-1.5">
                      <svg className="w-3.5 h-3.5 text-red-500" viewBox="0 0 24 24" fill="currentColor"><path d="M23.5 6.2a3 3 0 0 0-2.1-2.1C19.5 3.5 12 3.5 12 3.5s-7.5 0-9.4.6A3 3 0 0 0 .5 6.2 31.4 31.4 0 0 0 0 12c0 2 .2 3.9.5 5.8a3 3 0 0 0 2.1 2.1c1.9.5 9.4.5 9.4.5s7.5 0 9.4-.5a3 3 0 0 0 2.1-2.1c.3-1.9.5-3.8.5-5.8 0-2-.2-3.9-.5-5.8zM9.5 15.6V8.4l6.3 3.6-6.3 3.6z"/></svg>
                      YouTube Preview
                    </div>
                  </div>
                );
              }
              if (/\.(mp4|webm|ogg)(\?|$)/i.test(formData.videoUrl)) {
                return (
                  <div className="mt-3 rounded-lg overflow-hidden border border-gray-200">
                    <video src={formData.videoUrl} controls className="w-full max-h-48" preload="metadata" />
                  </div>
                );
              }
              return null;
            })()}
          </div>
        </section>

        {/* ── 6. SEO ── */}
        <section className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center gap-2 mb-4">
            <Search className="w-4 h-4 text-gray-400" />
            <h2 className="text-base font-semibold text-gray-900">SEO</h2>
          </div>
          <div className="grid gap-4">
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-sm text-gray-500">Meta Title</label>
                <span
                  className={`text-xs ${
                    formData.metaTitle.length > 60 ? "text-gray-900 font-medium" : "text-gray-400"
                  }`}
                >
                  {formData.metaTitle.length}/60
                </span>
              </div>
              <input
                type="text"
                className={inputClass}
                value={formData.metaTitle}
                onChange={(e) => updateField("metaTitle", e.target.value)}
                placeholder={formData.name || "Product title for search engines"}
              />
              <p className="text-xs text-gray-400 mt-1">Recommended 50–60 characters</p>
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-sm text-gray-500">Meta Description</label>
                <span
                  className={`text-xs ${
                    formData.metaDescription.length > 160 ? "text-gray-900 font-medium" : "text-gray-400"
                  }`}
                >
                  {formData.metaDescription.length}/160
                </span>
              </div>
              <textarea
                className={`${inputClass} resize-none`}
                rows={3}
                value={formData.metaDescription}
                onChange={(e) => updateField("metaDescription", e.target.value)}
                placeholder="Brief description for search engine results…"
              />
              <p className="text-xs text-gray-400 mt-1">Recommended 150–160 characters</p>
            </div>

            {/* SERP preview */}
            <div className="mt-2 p-4 border border-gray-100 rounded-lg bg-gray-50">
              <p className="text-xs text-gray-400 mb-2 flex items-center gap-1">
                <Globe className="w-3 h-3" />
                Search preview
              </p>
              <p className="text-sm text-blue-700 truncate">
                {formData.metaTitle || formData.name || "Product Title"}
              </p>
              <p className="text-xs text-green-700 truncate">{serpUrl}</p>
              <p className="text-xs text-gray-500 mt-0.5 line-clamp-2">
                {formData.metaDescription || "Add a meta description to see how this product appears in search results."}
              </p>
            </div>
          </div>
        </section>

        {/* ── 7. Sticky Action Bar ── */}
        <div className="flex gap-3 sticky bottom-4 bg-white p-4 rounded-lg border border-gray-200 shadow-lg">
          <Link
            href="/admin/products"
            className="flex-1 px-4 py-2.5 text-center text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm font-medium transition-colors"
          >
            Cancel
          </Link>
          <button
            type="submit"
            disabled={saving}
            className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-gray-900 text-white hover:bg-gray-800 rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
          >
            {saving ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Creating…
              </>
            ) : (
              <>
                <Package className="w-4 h-4" />
                Create Product
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
